const scrolltime = 6.5
const endtext = 'Kiitos katsomisesta!' Keväällä uudestaan!
const credits = [
    {'type': 'bigheading', 'text': 'Vauhtijuoksu+ 2025 tekemässä:'},
    {'type': 'heading', 'text': 'Vauhtijuoksu+-toimikunta 2025'},
    {'type': 'title', 'text': 'Päätuottaja'},
    {'type': 'responsible', 'text': 'jsloth'},
    {'type': 'title', 'text': 'Projektisihteeri'},
    {'type': 'responsible', 'text': 'sitronelli'},
    {'type': 'title', 'text': 'Huolto'},
    {'type': 'responsible', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'Health'},
    {'type': 'name', 'text': 'Itu'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'powerman'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'title', 'text': 'Grafiikka'},
    {'type': 'responsible', 'text': 'Timppasieni'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Karo'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'Stiivu'},
    {'type': 'title', 'text': 'Koodi'},
    {'type': 'responsible', 'text': 'Wild Penguin'},
    {'type': 'name', 'text': 'enk'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Runtu'},
    {'type': 'name', 'text': 'Spike_B'}
    {'type': 'name', 'text': 'T3mu'},
    {'type': 'title', 'text': 'Mainosmyynti'},
    {'type': 'responsible', 'text': 'Anni'},
    {'type': 'title', 'text': 'Sisältö'},
    {'type': 'responsible', 'text': 'naitsa'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'powerman'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'title', 'text': 'Tekniikka'},
    {'type': 'responsible', 'text': 'Aleksanteri'},
    {'type': 'name', 'text': 'Borb'},
    {'type': 'name', 'text': 'JapeDragoon'},
    {'type': 'name', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'Wild Penguin'},
    {'type': 'title', 'text': 'Viestintä'},
    {'type': 'responsible', 'text': 'Ituttaa'},
    {'type': 'name', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'MariS'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'heading', 'text': 'Tapahtumanaikainen toiminta'},
    {'type': 'name', 'text': 'Aleksanteri'},
    {'type': 'name', 'text': 'borb'},
    {'type': 'name', 'text': 'Drauce'},
    {'type': 'name', 'text': 'Elisene'},
    {'type': 'name', 'text': 'Health'},
    {'type': 'name', 'text': 'Ituttaa'},
    {'type': 'name', 'text': 'JapeDragoon'},
    {'type': 'name', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'jsloth'}, 
    {'type': 'name', 'text': 'Kablemo'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'Kyria'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'Mega_Tron'},
    {'type': 'name', 'text': 'naitsa'},
    {'type': 'name', 'text': 'Powerman'},
    {'type': 'name', 'text': 'Pokejaki'},
    {'type': 'name', 'text': 'Runtu'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'name', 'text': 'Timppasieni'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'name', 'text': 'Wild Penguin'},
    {'type': 'heading', 'text': 'Mukana pelaamassa'},
    {'type': 'name', 'text': 'Aivoapina'},
    {'type': 'name', 'text': 'Alaapo'},
    {'type': 'name', 'text': 'Angry Mandalorian'},
    {'type': 'name', 'text': 'Cartiss'},
    {'type': 'name', 'text': 'datadrako'},
    {'type': 'name', 'text': 'Elisene'},
    {'type': 'name', 'text': 'enk'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'Ituttaa'},
    {'type': 'name', 'text': 'JapeDragoon'},
    {'type': 'name', 'text': 'JefuDaMon'},
    {'type': 'name', 'text': 'Joppekoira'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Jughaz'},
    {'type': 'name', 'text': 'JustRoinatan'},
    {'type': 'name', 'text': 'Kablemo'},
    {'type': 'name', 'text': 'Kal3vi'},
    {'type': 'name', 'text': 'kannadan'},
    {'type': 'name', 'text': 'Leewo'},
    {'type': 'name', 'text': 'Lumoluuri'},
    {'type': 'name', 'text': 'M1Gen'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'MegaTron'},
    {'type': 'name', 'text': 'naitsa'},
    {'type': 'name', 'text': 'Örmynkörmy'},
    {'type': 'name', 'text': 'Pokejaki'},
    {'type': 'name', 'text': 'powerman'},
    {'type': 'name', 'text': 'Reeloy'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'Seinä'},
    {'type': 'name', 'text': 'SEPPAERAEINEN'},
    {'type': 'name', 'text': 'Sitronelli'},
    {'type': 'name', 'text': 'softmagus'},
    {'type': 'name', 'text': 'st0mba'},
    {'type': 'name', 'text': 'syksy'},
    {'type': 'name', 'text': 'Tohelot'},
    {'type': 'name', 'text': 'Tumi'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'name', 'text': 'WormEmperor'},
    {'type': 'name', 'text': 'Xazu'},
    {'type': 'heading', 'text': 'Tapahtuman musiikki'},
    {'type': 'name', 'text': 'Arttu Tuovinen'},
    {'type': 'name', 'text': 'borb'},
    {'type': 'name', 'text': 'Deerboy'},
    {'type': 'name', 'text': 'Janne Peltola'},
    {'type': 'name', 'text': 'Juze'},
    {'type': 'name', 'text': 'Migge'},
    {'type': 'name', 'text': 'milkyheart'},
    {'type': 'name', 'text': 'REINO'},
    {'type': 'name', 'text': 'Ringsir'},
    {'type': 'name', 'text': 'Snakebearer'},
    {'type': 'name', 'text': 'Tyrmävuori'},
    {'type': 'name', 'text': 'User Unknown'},
    {'type': 'name', 'text': 'Örmynkörmy'},
    {'type': 'heading', 'text': 'Yhteistyössä'},
    {'type': 'name', 'text': 'WWF'},
    {'type': 'name', 'text': 'PSOAS'},
    {'type': 'name', 'text': 'az.sh'},
    {'type': 'name', 'text': 'Nuvoo'},
    {'type': 'name', 'text': 'POP Pankki Pohjanmaa'},
    {'type': 'name', 'text': 'Rattoradio'},
    {'type': 'name', 'text': 'Retrogame Tycoon'},
    {'type': 'name', 'text': 'Teekkarilupi'},
    {'type': 'name', 'text': 'TEK'},
    {'type': 'name', 'text': 'Tiedot'},
    {'type': 'name', 'text': 'Tullisali'},
    {'type': 'name', 'text': 'Vectorama'},
]
