const scrolltime = 6.5
const endtext = 'Kiitos katsomisesta! <3'
const credits = [
    {'type': 'bigheading', 'text': 'Vauhtijuoksu 2026 tekemässä:'},
    {'type': 'heading', 'text': 'Vauhtijuoksu-toimikunta 2026'},
    {'type': 'title', 'text': 'Päätuottaja'},
    {'type': 'responsible', 'text': 'sitronelli'},
    {'type': 'title', 'text': 'Projektisihteeri'},
    {'type': 'responsible', 'text': 'jsloth'},
    {'type': 'title', 'text': 'Huolto'},
    {'type': 'responsible', 'text': 'MegaTron'},
    {'type': 'name', 'text': 'Health'},
    {'type': 'name', 'text': 'Itu'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'powerman'},
    {'type': 'name', 'text': 'Tahiteea'},
    {'type': 'name', 'text': 'Anni'},
    {'type': 'title', 'text': 'Grafiikka'},
    {'type': 'responsible', 'text': 'Stiivu'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Reeloy'},
    {'type': 'name', 'text': 'Karo'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'Timppasieni'},
    {'type': 'title', 'text': 'Koodi'},
    {'type': 'responsible', 'text': 'Wild Penguin'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Tahiteea'},
    {'type': 'name', 'text': 'Spike_B'},
    {'type': 'name', 'text': 'T3mu'},
    {'type': 'title', 'text': 'Mainosmyynti'},
    {'type': 'responsible', 'text': 'Örmynkörmy'},
    {'type': 'title', 'text': 'Sisältö'},
    {'type': 'responsible', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'Health'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'naitsa'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'powerman'},
    {'type': 'name', 'text': 'st0mba'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'title', 'text': 'Tekniikka'},
    {'type': 'responsible', 'text': 'JapeDragoon'},
    {'type': 'name', 'text': 'Borb'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'Kurkkumopo'},
    {'type': 'name', 'text': 'st0mba'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'MegaTron'},
    {'type': 'title', 'text': 'Viestintä'},
    {'type': 'responsible', 'text': 'Reeloy'},
    {'type': 'name', 'text': 'Kurkkumopo'},
    {'type': 'name', 'text': 'Keksiperkele'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'heading', 'text': 'Tapahtumanaikainen toiminta'},
    {'type': 'name', 'text': 'borb'},
    {'type': 'name', 'text': 'Health'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'Ituttaa'},
    {'type': 'name', 'text': 'JapeDragoon'},
    {'type': 'name', 'text': 'JoppeKoira'},
    {'type': 'name', 'text': 'jsloth'}, 
    {'type': 'name', 'text': 'Kablemo'},
    {'type': 'name', 'text': 'Kurkkumopo'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'Kyria'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'MegaTron'},
    {'type': 'name', 'text': 'naitsa'},
    {'type': 'name', 'text': 'Powerman'},
    {'type': 'name', 'text': 'punaliitu'},
    {'type': 'name', 'text': 'st0mba'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'name', 'text': 'Tahiteea'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'name', 'text': 'Wild Penguin'},
    {'type': 'heading', 'text': 'Mukana pelaamassa'},
    {'type': 'name', 'text': 'Aivoapina'},
    {'type': 'name', 'text': 'Angry Mandalorian'},
    {'type': 'name', 'text': 'borb'},
    {'type': 'name', 'text': 'Cartiss'},
    {'type': 'name', 'text': 'ConfirmDeny'},
    {'type': 'name', 'text': 'Drauce'},
    {'type': 'name', 'text': 'Elisene'},
    {'type': 'name', 'text': 'enk'},
    {'type': 'name', 'text': 'Horus'},
    {'type': 'name', 'text': 'Ituttaa'},
    {'type': 'name', 'text': 'JapeDragoon'},
    {'type': 'name', 'text': 'JefuDaMon'},
    {'type': 'name', 'text': 'Joppekoira'},
    {'type': 'name', 'text': 'jsloth'},
    {'type': 'name', 'text': 'Jughaz'},
    {'type': 'name', 'text': 'Keksi'},
    {'type': 'name', 'text': 'Kablemo'},
    {'type': 'name', 'text': 'Komentaja'},
    {'type': 'name', 'text': 'Lumoluuri'},
    {'type': 'name', 'text': 'Matsku'},
    {'type': 'name', 'text': 'Matto'},
    {'type': 'name', 'text': 'M1Gen'},
    {'type': 'name', 'text': 'MegaTron'},
    {'type': 'name', 'text': 'Mr Randomizer'},
    {'type': 'name', 'text': 'naitsa'},
    {'type': 'name', 'text': 'olenananas'},
    {'type': 'name', 'text': 'powerman'},
    {'type': 'name', 'text': 'punaliitu'},
    {'type': 'name', 'text': 'Reeloy'},
    {'type': 'name', 'text': 'Samoyed'},
    {'type': 'name', 'text': 'Seinä'},
    {'type': 'name', 'text': 'Skelly'},
    {'type': 'name', 'text': 'sitronelli'},
    {'type': 'name', 'text': 'softmagus'},
    {'type': 'name', 'text': 'Svanhildr'},
    {'type': 'name', 'text': 'Tohelot'},
    {'type': 'name', 'text': 'teerex'},
    {'type': 'name', 'text': 'Vaipperi'},
    {'type': 'name', 'text': 'Wild Penguin'},
    {'type': 'name', 'text': 'Xazu'},
    {'type': 'name', 'text': 'Örmynkörmy'},
    {'type': 'heading', 'text': 'Tapahtuman musiikki'},
    {'type': 'name', 'text': 'Arttu Tuovinen'},
    {'type': 'name', 'text': 'borb'},
    {'type': 'name', 'text': 'Deerboy'},
    {'type': 'name', 'text': 'Janne Peltola'},
    {'type': 'name', 'text': 'Juze'},
    {'type': 'name', 'text': 'maiu'},
    {'type': 'name', 'text': 'Matias Lehtoranta'},
    {'type': 'name', 'text': 'Migge'},
    {'type': 'name', 'text': 'milkyheart'},
    {'type': 'name', 'text': 'REINO'},
    {'type': 'name', 'text': 'Ringsir'},
    {'type': 'name', 'text': 'Snakebearer'},
    {'type': 'name', 'text': 'Tyrmävuori'},
    {'type': 'name', 'text': 'User Unknown'},
    {'type': 'name', 'text': 'Örmynkörmy'},
    {'type': 'heading', 'text': 'Yhteistyössä'},
    {'type': 'name', 'text': 'Sairaalaklovnit ry'},
    {'type': 'name', 'text': 'Töimisto'},
    {'type': 'name', 'text': 'az.sh'},
    {'type': 'name', 'text': 'Rattoradio'},
    {'type': 'name', 'text': 'Vectorama'},
    {'type': 'name', 'text': 'Loren Lemcke Games'},
    {'type': 'name', 'text': 'Domesticated Ant Games'},
    {'type': 'name', 'text': 'System Erasure'},
    {'type': 'name', 'text': 'Teekkarilupi'},
    {'type': 'name', 'text': 'Upcloud'},
    {'type': 'name', 'text': 'TEK'},
    {'type': 'name', 'text': 'Kili'},
    {'type': 'name', 'text': 'Oikia'},
    {'type': 'name', 'text': 'Putaan Pulla'},
    {'type': 'name', 'text': 'Elovena'},
]
